### ISSUE TITLE
Can I use a custom dataset for training?

### ISSUE THREAD

**Issue by rizentan** [shubha07m/On-device-computer-vision-experiments-with-IoT#6]
Thank you for your work! 
Can I use a custom dataset for training?

**Comment by shubha07m** [comment]
Sure you can train your custom dataset for YOLOv8! Two options:

**Fine-tune pre-trained weights:**
Use a pre-trained model (.pt from **multimodal_trained_weights**) with your data. Often a faster option.

**Train from scratch (advanced):**
Use the yolo_phantom.yaml configuration (in **models/v8**) with your data. 
Consider citing our [paper](https://doi.org/10.48550/arXiv.2402.07894) if you find this model useful, hope this helps!

**Comment by shubha07m** [comment]
Hello again,

As mentioned in paper, yolo phantom has been built on using Ultralytics YOLOV8 as a foundation model. So, for training procedure you can refer to [yolov8 repo](https://github.com/ultralytics/ultralytics).

You can refer to [this](https://github.com/ultralytics/ultralytics/tree/main/ultralytics/cfg/models/v8) to see their existing model architectures, and [here](https://github.com/ultralytics/ultralytics/tree/main/ultralytics/nn) to see their usage of different modules.

Now, yolo phantom used yolov8's repo and enhanced new [yolo phantom](https://github.com/shubha07m/On-device-computer-vision-experiments-with-IoT/blob/main/yolo_phantom/cfg/models/v8/yolo_phantom.yaml) architectures, as well as novel Phantom Convolution or [PhantomConv](https://github.com/shubha07m/On-device-computer-vision-experiments-with-IoT/blob/main/yolo_phantom/nn/modules/conv.py) as a new convolution block.

I suggest you to start cloning the yolov8 repo and observe the file structure carefully to compare the improvements performed here. For more information, you may please refer to the paper. Hope this helps!

**Comment by rizentan** [comment]
Thank you again for your reply, it has been very helpful to me.

**Comment by shubha07m** [comment]
I'm glad it helped!

**Comment by rizentan** [comment]
I generated a "best. pt" file using a custom dataset, but I encountered an error when executing it using "from_pi/object_calert_proto. py":

_WARNING ⚠️ best.pt appears to require 'project', which is not in ultralytics requirements.
AutoInstall will run now for 'project' but this feature will be removed in the future.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt'
requirements: Ultralytics requirement ['project'] not found, attempting AutoUpdate..._

I am currently using yolov9, Is the YOLO model incorrect?

**Comment by shubha07m** [comment]
My models should be compatible with yolov8 and yolov8.1, however yolov9 being a non - Ultralytics family model (like Ultralytics yolov5, yolov8 etc.) might needs additional customizations / functions. Try to check the source of error (from which file / which functions specifically).

**Comment by mahmoudmhashem** [comment]
I still don't know how to train your model you mentioned that I should follow ultralytics documentation I can train a yolo8 but not your model How your model is integrated into ultralytics.

I've cloned your repo and run the following but it gives me an error

```py
from ultralytics import YOLO

model = YOLO("yolo_phantom/cfg/models/v8/yolo_phantom.yaml")
```

the error

m = getattr(torch.nn, m[3:]) if "nn." in m else globals()[m]  # get module
KeyError: 'PhantomConv'

**Comment by shubha07m** [comment]
Hello,

There was some major restructuring of file on main Ultralytics repo. So most of the files had to be arranged to match that structure. I have also added the step-by-step instructions to use YOLO Phantom now. Please follow the steps and let me know, if you are able to use it now.

Hope this helps!

**Comment by mahmoudmhashem** [comment]
Yes, it helps a lot. Thanks for your support.
