### ISSUE TITLE
cannot import 'SETTINGS_YAML' from ultralytics.ultils

### ISSUE THREAD

**Issue by pikamanh** [shubha07m/On-device-computer-vision-experiments-with-IoT#8]
I had clone your project and followed the instructions to run the YOLO Phantom. But I have the issue when I import ultralytics in file 'yolophantom_testing.ipynb' that in the __init__.py of **cfg folder** is not working with SETTINGS_YAML. This code in your modified **cfg folder**. Can someone help me to fix it?

**Comment by shubha07m** [comment]
I believe recently there are some major restructuring in YOLO Ultralytics, which probably caused this issue. I suggest, install the latest version of Ultralytics YOLO from GitHub / pip, then try to recreate the architectural changes I did in Ultralytics yolov8n if possible. It may also be possible the current version of YOLO Ultralytics may or may not support the changes done in YOLO Phantom. I will try to reproduce YOLO Phantom locally with the latest version of YOLO Ultralytics and update the YOLO Phantom Github repo.

**Comment by shubha07m** [comment]
@pikamanh : I have mirrored the restructuring in current Ultralytics YOLO , as well as updated the instructions to reflect the changes done for YOLO Phantom, follow the updated instructions in readme and let me know if it works.
